apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    name: admin-app-pod
    type: frontend
