apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: results
  name: results
spec:
  replicas: 1
  selector:
    matchLabels:
      name: results-app-pod
      type: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: results-app-pod
        type: frontend
    spec:
      containers:
        - image: samuel3105/node_results
          name: results
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - mountPath: /node_results
              name: results-claim0
      restartPolicy: Always
      volumes:
        - name: results-claim0
          persistentVolumeClaim:
            claimName: results-claim0
