apiVersion: v1
kind: Service
metadata:
  labels:
    app: results
  name: results
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    name: results-app-pod
    type: frontend

